configuration: Release

environment:
  DOCKER_USER:
    secure: TUkS9BRix2EaX6263HzABg==
  DOCKER_PASS:
    secure: Q1RiZsWAMyXDY9VF6erhkg==

image: Ubuntu

before_build:
- dotnet build ./build/_build.csproj -v m -c Release

build_script:
- dotnet run --project ./build/_build.csproj Compile

deploy_script:
- dotnet run --project ./build/_build.csproj PublishDockerImage --DockerUser $env:DOCKER_USER --DockerPass $env:DOCKER_PASS
